### ISSUE TITLE
Create a PowerPoint for Project for Demonstration

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#18]

**Comment by cdasilvasantos** [comment]
Started!

**Comment by m1chaeldaniels** [comment]
PowerPoint : https://docs.google.com/presentation/d/13q4i5SQISLtWtEunGKS2gFTY9_MA9xc8ofNYWPDxyZc/edit#slide=id.ge96fd93d6a_0_18749
