### ISSUE TITLE
Testimonals need to be added/fitted onto landing page

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#23]
Show proof our site/restaurant is delivering

- could be something like (Ranked top 10 in Newark)
- Forbes top 30 restaurants

**Comment by cdasilvasantos** [comment]
Done, added customer reviews

**Comment by m1chaeldaniels** [comment]
![Uploading Screenshot 2023-12-19 at 9.40.26 AM.png…]()
