### ISSUE TITLE
Include Imagery that exemplifies our experience offered

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#24]
User will want to see a page that not only is for a steakhouse, but a steakhouse that will give them a feeling of luxury, an experience. Which ties to our name LuxCore. Luxury at our core. Selling the meaning. ex Coffee on a coffee shop doesn't excite anyone as they can get coffee anywhere. We need to create visuals that portray something beyond steak. Our restaurants craftsmanship and delicacy.

**Comment by m1chaeldaniels** [comment]
I believe we have this, we have excellent images showcasing luxury and a peaceful quality experience

**Comment by cdasilvasantos** [comment]
Done!

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 9 02 41 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/8a4cab80-78a9-4db6-bee7-40930e03f07b)
