### ISSUE TITLE
GDRP Working and installed

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#26]

**Comment by cdasilvasantos** [comment]
Done!

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 8 44 02 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/60c19183-7485-45e1-b3f4-8177e6f4f51c)
![Screenshot 2023-12-19 at 8 44 37 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/d4b41faa-9bc5-4f53-86e3-beac9edcecfa)
