### ISSUE TITLE
maintain a consistent css color for site and separate pages

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#39]

**Comment by cdasilvasantos** [comment]
Done!

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 9 39 19 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/b5df8992-39fd-41cf-9d1f-4bc580a647f9)
