### ISSUE TITLE
Redo footer on figma as new design has been planned

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#42]

**Comment by cdasilvasantos** [comment]
Done!

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 9 02 57 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/6fdd933c-6790-4ebd-a7f8-7506d1a30aaf)
