### ISSUE TITLE
Continue testing mail chimp to ensure records are populating

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#43]

**Comment by cdasilvasantos** [comment]
Michael confirmed they are

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 9 06 17 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/42a533f7-fab3-438b-af47-6aa4cce836d1)
