### ISSUE TITLE
create personal pages for both owners in about section

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#56]

**Comment by cdasilvasantos** [comment]
Owners have a section to themselves

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 9 02 41 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/fb03ad20-9007-45ce-bd66-b457170475e7)
