### ISSUE TITLE
Create cookie consent policy, have real terms of use

### ISSUE THREAD

**Issue by m1chaeldaniels** [cdasilvasantos/is218-group-project#66]

**Comment by cdasilvasantos** [comment]
Michael created the cookie consent banner

**Comment by m1chaeldaniels** [comment]
![Screenshot 2023-12-19 at 8 44 37 AM](https://github.com/cdasilvasantos/is218-group-project/assets/117040399/c72bb9ab-b059-4299-97af-26afd5c2db9f)
